version: '3'
services:
  ezhome:
    restart: always
    build: .
    environment:
      - PORT=3002
    ports:
      - '3002:3002'
    volumes:
      - ./logs:/usr/src/app/dist/logs
    env_file:
      - .env